services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: attribution
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d attribution"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports: ["2181:2181"]

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    volumes:
      - ./services/api/app:/app/app
      - ./scripts:/app/scripts
      - ./batch:/app/batch
      - ./libs/jars:/app/jars
      - ./data:/app/data
    environment:
      APP_ENV: local
      POSTGRES_DSN: postgresql+psycopg://app:app@postgres:5432/attribution
      REDIS_URL: redis://redis:6379/0
    ports: ["8000:8000"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  stream_processor:
    build:
      context: .
      dockerfile: services/stream_processor/Dockerfile
    environment:
      APP_ENV: local
      KAFKA_BOOTSTRAP: kafka:9092
      KAFKA_TOPIC_EVENTS: ad_events
      KAFKA_CONSUMER_GROUP: attribution-stream-v1
      POSTGRES_DSN: postgresql+psycopg://app:app@postgres:5432/attribution
      REDIS_URL: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started

networks:
  default:
    name: carbon-attrib